version: "3.9"

services:
  lp_kay:
    build: .
    container_name: lp_kay
    ports:
      - "8080:80" # localhost:3000 -> nginx port 80
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    driver: bridge